# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Source code formatter
      run: |
        flake8 .
    - name: Test with pytest
      run: |
        pytest
    - shell: bash
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        echo "$PASSWORD"
    - name: Discord Notifier
      uses: fateyan/action-discord-notifier@v1.2.0
      with:
        webhook: https://discord.com/api/webhooks/882220403878137906/uroRgnc3sTGv5600d7Mkk6ejx1GZBTYQhAYj858JZZ3VNQprmQPfwNhp6k4u9czkbKb8
        message-title: PEA ⚡️💕✌🏻
        python -m pip install --upgrade pip
